Do not rely on pyproject macros
These macros are available since fedora31, for
centos8 these are not available, automaticbr
generation fails with below on rhel8 if these are used.

error: Missing rpmlib features for python-pint-0.10.1-1.fc32.noarch
error:  rpmlib(DynamicBuildRequires) <= 4.15.0-1